=== Agence-DnD/adobe-stock-integration/AdobeStockAsset/etc/adobe_stock_requests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="requests">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="request">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="filters">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="filter" type="filter" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="resultColumns">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="column" type="column" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="from"/>
                            <xs:element type="xs:string" name="size"/>
                            <xs:element type="xs:string" name="locale"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="name"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="filter">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="field" use="required"/>
    </xs:complexType>
    <xs:complexType name="column">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="field" use="required"/>
    </xs:complexType>
</xs:schema>

=== Agence-DnD/adobe-stock-integration/AdobeStockImage/etc/adobe_stock_requests.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<requests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_AdobeStockAsset:etc/adobe_stock_requests.xsd">
    <request name="adobe_stock_image_search">
        <filters>
            <filter name="words" field="words"/>
            <filter name="content_type_filter" field="content_type"/>
            <filter name="offensive_filter" field="offensive"/>
            <filter name="isolated_filter" field="isolated"/>
            <filter name="orientation_filter" field="orientation"/>
            <filter name="colors_filter" field="colors"/>
            <filter name="premium_filter" field="premium"/>
        </filters>
        <resultColumns>
            <column name="nb_results" field="NB_RESULTS"/>
            <column name="id" field="ID"/>
            <column name="COMP_URL" field="COMP_URL"/>
        </resultColumns>
        <from>0</from>
        <size>32</size>
        <locale>En_en</locale>
    </request>
</requests>
